#!/usr/bin/env python3

import os
import argparse
import re
from datetime import datetime
from PIL import Image
from PIL.ExifTags import TAGS


def get_exif_time(filename):
    img = Image.open(filename)
    
    if img._getexif() is None:
        return ''
    exif = {TAGS.get(tag, tag):value for tag,value in img._getexif().items()}

    return exif['DateTimeOriginal']  \
           if exif['DateTimeOriginal'] is not None  \
           else ''


def rename_all_files(dir, tag, date):
    predicate = lambda filename: (get_exif_time(filename), filename)
    file_list = sorted(os.listdir(dir), key=predicate)

    file_map = [(file, 
                 '{:03}_{}_{:%Y-%m-%d}.jpeg'.format(i, 
                                                    tag, 
                                                    datetime.strptime(get_exif_time(file), '%Y:%m:%d %H:%M:%S')  \
                                                        if get_exif_time(file)  \
                                                        else date)
                )  \
                for file,i in zip(file_list, range(1, len(file_list) + 1))]

    # Rename to prevent name clashes first 
    for old,new in file_map:
        print('{} -> {} [{}]'.format(old, new, get_exif_time(old)))
        os.rename(old, old + '.tmp')

    # Final rename
    for old,new in file_map:
        os.rename(old + '.tmp', new)


def date_string(input):
    try:
        return datetime.strptime(input, '%Y-%m-%d')
    except:
        raise argparse.ArgumentError()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Rename files in a directory to the format XXX_tag_date')
    parser.add_argument('tag', help='Tag to include in all file names')
    parser.add_argument('date', type=date_string, help='The date to append to all file names. Format: YYYY-MM-DD')
    # TODO Make paths relative to 'directory'
    # parser.add_argument('directory', help='The directory containing the files to rename')
    args = parser.parse_args()

    rename_all_files('.', args.tag, args.date)

