#!/usr/bin/env python3

import os
import argparse
import re
from datetime import datetime
from PIL import Image
from PIL.ExifTags import TAGS


def get_exif_time(filename):
    img = Image.open(filename)
    
    if img._getexif() is None:
        return ''
    exif = {TAGS.get(tag, tag):value for tag,value in img._getexif().items()}

    return exif['DateTimeOriginal']  \
           if exif['DateTimeOriginal'] is not None  \
           else ''


# TODO Do a pre-rename first to prevent overwriting files
def rename_all_files(dir, tag, date):
    predicate = lambda filename: (get_exif_time(filename), filename)
    file_list = sorted(os.listdir(dir), key=predicate)

    for file,i in zip(file_list, range(1, len(file_list) + 1)):
        new_filename = '{:03}_{}_{}.jpeg'.format(i, tag, date)
        os.rename(file, new_filename)
        print('{} -> {} [{}]'.format(file, new_filename, get_exif_time(new_filename)))


def date_string(input):
    if re.match('^20\d\d-[01]\d-[03]\d$', input):
        return input
    else:
        raise argparse.ArgumentError()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Rename files in a directory to the format XXX_tag_date')
    parser.add_argument('tag', help='Tag to include in all file names')
    parser.add_argument('date', type=date_string, help='The date to append to all file names. Format: YYYY-MM-DD')
    parser.add_argument('directory', help='The directory containing the files to rename')
    args = parser.parse_args()

    rename_all_files(args.directory, args.tag, args.date)

